In [5]:
print(df_2021.columns.tolist())

['기준연도', '자치구명', '행정동명', '행정동코드', 'IVI', 'CDI', 'RII', 'CCI', 'CCI_rank', 'CCI_grade', 'IVI_top30_flag', 'CDI_top30_flag', 'RII_top30_flag', 'triple_high_flag', 'risk_type']

In [ ]:
import pandas as pd
import geopandas as gpd

# 데이터 불러오기
df_2021 = pd.read_csv('final_crisis_index_by_dong_2021.csv')
gdf_2021 = gpd.read_file('final_crisis_index_by_dong_2021.gpkg')

# RII_grade가 데이터에 없으므로, RII_top30_flag로 대체해서 표를 만듭니다.
columns_to_show = ['자치구명', '행정동명', 'RII', 'RII_top30_flag', 'CCI', 'CCI_rank', 'risk_type']
top_10_rii = df_2021.nlargest(10, 'RII')[columns_to_show]

print("--- RII 상위 10개 행정동 ---")
display(top_10_rii)

# 상위 10개 중 복합위기 최고위험지역(triple_high_flag == 1) 포함 여부
triple_high_dongs = df_2021[df_2021['triple_high_flag'] == 1]
top_10_in_triple_high = top_10_rii[top_10_rii['행정동명'].isin(triple_high_dongs['행정동명'])]

# RII_grade가 데이터에 없으므로, RII_top30_flag로 대체해서 표를 만듭니다.
columns_to_show = ['자치구명', '행정동명', 'RII', 'RII_top30_flag', 'CCI', 'CCI_rank', 'risk_type']
top_10_rii = df_2021.nlargest(10, 'RII')[columns_to_show]

print("--- RII 상위 10개 행정동 ---")
display(top_10_rii)

# 상위 10개 중 복합위기 최고위험지역(triple_high_flag == 1) 포함 여부
triple_high_dongs = df_2021[df_2021['triple_high_flag'] == 1]
top_10_in_triple_high = top_10_rii[top_10_rii['행정동명'].isin(triple_high_dongs['행정동명'])]

print("\n--- 상위 10개 중 복합위기 최고위험지역 포함 행정동 ---")
display(top_10_in_triple_high)

--- RII 상위 10개 행정동 ---

     자치구명   행정동명       RII  RII_top30_flag       CCI  CCI_rank    risk_type
158   노원구   월계2동  0.642672               1  0.714276         1  복합위기 최고위험지역
157   노원구   월계1동  0.640463               1  0.644950        12     수해 단일취약형
166   노원구   상계1동  0.637440               1  0.625596        22     수해 단일취약형
93   동대문구  답십리1동  0.636016               1  0.607324        40     수해 단일취약형
89   동대문구   장안1동  0.619531               1  0.584980        61     수해 단일취약형
190   은평구   응암3동  0.602871               1  0.655318        10   사회고립+수해취약형
86   동대문구   전농1동  0.578086               1  0.639786        14   사회고립+수해취약형
154   도봉구    창5동  0.578029               1  0.603404        42     수해 단일취약형
88   동대문구  답십리2동  0.578004               1  0.617531        31   사회고립+수해취약형
219   마포구    서강동  0.577971               1  0.593317        48     수해 단일취약형

--- RII 상위 10개 행정동 ---

     자치구명   행정동명       RII  RII_top30_flag       CCI  CCI_rank    risk_type
158   노원구   월계2동  0.642672               1  0.714276         1  복합위기 최고위험지역
157   노원구   월계1동  0.640463               1  0.644950        12     수해 단일취약형
166   노원구   상계1동  0.637440               1  0.625596        22     수해 단일취약형
93   동대문구  답십리1동  0.636016               1  0.607324        40     수해 단일취약형
89   동대문구   장안1동  0.619531               1  0.584980        61     수해 단일취약형
190   은평구   응암3동  0.602871               1  0.655318        10   사회고립+수해취약형
86   동대문구   전농1동  0.578086               1  0.639786        14   사회고립+수해취약형
154   도봉구    창5동  0.578029               1  0.603404        42     수해 단일취약형
88   동대문구  답십리2동  0.578004               1  0.617531        31   사회고립+수해취약형
219   마포구    서강동  0.577971               1  0.593317        48     수해 단일취약형

--- 상위 10개 중 복합위기 최고위험지역 포함 행정동 ---

    자치구명  행정동명       RII  RII_top30_flag       CCI  CCI_rank    risk_type
158  노원구  월계2동  0.642672               1  0.714276         1  복합위기 최고위험지역

In [8]:
# RII_grade >= 4 대신, RII 상위 30%(RII_top30_flag == 1)이면서 최고위험지역이 아닌 곳 찾기
high_rii_low_cci = df_2021[(df_2021['RII_top30_flag'] == 1) & (df_2021['triple_high_flag'] == 0)]

print("--- RII는 상위권이지만 최고위험지역이 아닌 예시 ---")
display(high_rii_low_cci[['자치구명', '행정동명', 'RII', 'CCI', 'IVI', 'CDI']])

--- RII는 상위권이지만 최고위험지역이 아닌 예시 ---

    자치구명   행정동명       RII       CCI       IVI       CDI
0    종로구    사직동  0.399414  0.550882  0.443458  0.809775
2    종로구    부암동  0.368506  0.586746  0.408905  0.982827
15   종로구  청운효자동  0.491522  0.611841  0.399484  0.944518
21    중구    장충동  0.368506  0.592166  0.423844  0.984148
22    중구    광희동  0.491522  0.592217  0.521588  0.763540
..   ...    ...       ...       ...       ...       ...
413  강동구   암사3동  0.403634  0.539008  0.247736  0.965654
415  강동구   천호3동  0.396905  0.557521  0.428894  0.846764
422  강동구   천호2동  0.397842  0.510114  0.431045  0.701453
423  강동구     길동  0.452954  0.482389  0.373340  0.620872
424  구로구   오류2동  0.428030  0.560336  0.377153  0.875826

[117 rows x 6 columns]

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# 한글 폰트 깨짐 방지 (Windows 기준)
plt.rc('font', family='Malgun Gothic') 

# RII_grade별 행정동 수 막대그래프
plt.figure(figsize=(8, 5))
sns.countplot(data=df_2021, x='RII_grade', palette='Blues')
plt.title('RII 등급별 행정동 수')
plt.show()

# 자치구별 평균 RII
gu_mean_rii = df_2021.groupby('자치구명')['RII'].mean().sort_values(ascending=False)
plt.figure(figsize=(12, 6))
gu_mean_rii.plot(kind='bar', color='skyblue')
plt.title('자치구별 평균 RII')
plt.xticks(rotation=45)
plt.show()

In [ ]:
# 2019~2021 데이터 불러오기
df_time = pd.read_csv('rii_by_dong_2019_2021.csv')

# 2019~2021 데이터 불러오기
df_time = pd.read_csv('rii_by_dong_2019_2021.csv')

yearly_trend = df_time.groupby('기준연도')['RII'].mean()

print("--- 연도별 평균 RII 변화 추이 ---")
display(yearly_trend)

--- 연도별 평균 RII 변화 추이 ---

기준연도
2019    0.143455
2020    0.436425
2021    0.309525
Name: RII, dtype: float64